# Generated by Django 5.2.5 on 2026-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade_pessoas',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de pessoas'),
        ),
        migrations.AddField(
            model_name='sala',
            name='capacidade',
            field=models.PositiveIntegerField(default=30, verbose_name='Capacidade máxima'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da sala'),
        ),
    ]
