# Generated by Django 5.2.5 on 2026-02-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da sala'),
        ),
    ]
