# Generated by Django 5.2.5 on 2026-02-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_sala_nome'),
        ('webapp', '0003_reserva_quantidade_pessoas_sala_capacidade_and_more'),
    ]

    operations = [
    ]
