# Generated by Django 5.2.5 on 2026-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_merge_20260224_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('laboratorio', 'Laboratório'), ('auditorio', 'Auditório'), ('comum', 'Sala Comum'), ('outro', 'Outro')], default='comum', max_length=20, verbose_name='Tipo de sala'),
        ),
    ]
