# Generated by Django 5.2.5 on 2026-02-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_merge_20260224_1700'),
        ('webapp', '0005_sala_tipo'),
    ]

    operations = [
    ]
