# Generated by Django 5.2.5 on 2026-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_merge_0004_merge_20260224_1700_0005_sala_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='check_in_realizado',
            field=models.BooleanField(default=False, verbose_name='Check-in realizado'),
        ),
    ]
